version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    insecure-external-code-execution: allow
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "⬆️"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "⬆️"
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
        interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"
    commit-message:
      prefix: "⬆️"
