# .readthedocs.yml
version: 2
submodules:
  include:
     - pyvista
  recursive: true
python:
  version: 3.7
  install:
    - requirements: requirements.txt  # must contain "readthedocs-custom-steps"
