contact_links:
  - name: Ideas
    url: https://github.com/pyvista/pyvista/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Questions
    url: https://github.com/pyvista/pyvista/discussions/new?category=q-a
    about: Ask the community for help
  - name: Show and tell
    url: https://github.com/pyvista/pyvista/discussions/new?category=show-and-tell
    about: Show off something you've made
