body:
  - type: markdown
    attributes:
      value: |
          Thanks for taking the time to open this discussion to help improve PyVista!
          We don't use the General category.
          Please select other categories.
