blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/tkoyama010/pyvista-doc-translations/discussions
    about: For general questions and discussions
