name: Feature Request
description: Request that a feature be added to PyVista
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to open this issue to help improve PyVista!
  - type: textarea
    id: feature-details
    attributes:
      label: Describe the feature you would like to be added.
      description: |
        Provide a clear and concise description of what you would like added.
      placeholder: Tell us what you see!
      value: "I have an idea for a new feature!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/pyvista/pyvista/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
