name: pyvista-doc-auto-update
on:
  pull_request:  # Uses cache
  workflow_dispatch:  # Able to not use cache by user demand
    inputs:
      cache:
        description: 'Use build cache'
        required: false
        default: true
  # No cache enabled for `schedule` and `push`
  schedule:
    - cron: '0 0 * * *'  # once a day on main
  push:
    tags:
      - '*'
    branches:
      - main
env:
  USE_CACHE: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.cache == 'true') || (github.event_name == 'pull_request') || (github.event_name == 'push') }}
jobs:
  script:
    runs-on: ubuntu-20.04
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Get Job URL
      uses: Tiryoh/gha-jobid-action@v0
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: script
    - name: checkout with submodule
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends python3-setuptools
        sudo apt-get install -y --no-install-recommends libgl1-mesa-dev xvfb ffmpeg
        sudo apt-get install -y --no-install-recommends python3-venv
        sudo apt-get install -y --no-install-recommends libgl1-mesa-glx
        sudo apt-get install -y --no-install-recommends python3-tk pandoc
        pip install -U pip setuptools wheel
        pip install -r ./requirements.txt
    - name: Cache Sphinx-Gallery Examples
      uses: actions/cache@v2
      if: env.USE_CACHE == 'true'
      with:
        path: pyvista/doc/examples/
        key: doc-examples-${{ hashFiles('pyvista/pyvista/_version.py') }}
    - name: Cache docs _build directory
      uses: actions/cache@v2
      if: env.USE_CACHE == 'true'
      with:
        path: pyvista/doc/_build/
        key: doc-_build-${{ hashFiles('pyvista/pyvista/_version.py') }}-${{ hashFiles('doc/conf.py') }}
    - name: Cache autosummary
      uses: actions/cache@v2
      if: env.USE_CACHE == 'true'
      with:
        path: pyvista/**/_autosummary/*.rst
        key: autosummary-rst-${{ hashFiles('pyvista/pyvista/_version.py') }}
    - name: update
      env:
        SPHINXINTL_TRANSIFEX_USERNAME: api
        SPHINXINTL_TRANSIFEX_PROJECT_NAME: pyvista-doc
        TX_TOKEN: ${{ secrets.TX_TOKEN }}
      run: |
        set -x
        git submodule update --remote
        export DISPLAY=:99.0
        export PYVISTA_OFF_SCREEN=True
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        set +x
        rm ./locale/examples/*/*.py
        mv ./locale/examples ./pyvista/doc
        cd pyvista
        make -C doc html SPHINXOPTS="-w build_errors.txt -N"
        cd ../
        sh ./locale/update.sh
        ls ./pyvista/doc/examples
        mv ./pyvista/doc/examples ./locale
        ls ./pyvista/doc/images
        rm -Rf ./locale/images
        mv ./pyvista/doc/images ./locale
    - name: commit
      if: contains(github.event.head_commit.message, '[ci skip]') == false && contains(github.ref, 'main')
      env:
        JOB_ID: ${{ steps.jobs.outputs.job_id }}
        HTML_URL: ${{ steps.jobs.outputs.html_url }}
      run: |
        git config --global user.email $GITHUB_REPOSITORY
        git config --global user.name $GITHUB_REPOSITORY
        git add .
        git commit --allow-empty -m "[ci skip] $JOB_ID
        $HTML_URL"
        git remote -v
        git remote add github git@github.com:$GITHUB_REPOSITORY.git
        git push github main
