name: pyvista-doc-auto-update
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Get Job URL
      uses: Tiryoh/gha-jobid-action@v0
      id: jobs
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        job_name: script
    - name: checkout with submodule
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - name: Setup SSH
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: install
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends python3-setuptools
        sudo apt-get install -y --no-install-recommends libgl1-mesa-dev xvfb ffmpeg
        sudo apt-get install -y --no-install-recommends python3-venv
        sudo apt-get install -y --no-install-recommends libgl1-mesa-glx
        python3 -m venv /home/runner/work/.venv
        source /home/runner/work/.venv/bin/activate
        pip install -U pip setuptools wheel
        pip install -r ./requirements.txt
        deactivate
    - name: update
      env:
        SPHINXINTL_TRANSIFEX_USERNAME: api
        SPHINXINTL_TRANSIFEX_PROJECT_NAME: pyvista-doc
        TX_TOKEN: ${{ secrets.TX_TOKEN }}
      run: |
        source /home/runner/work/.venv/bin/activate
        set -x
        export DISPLAY=:99.0
        export PYVISTA_OFF_SCREEN=True
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        set +x
        rm ./locale/examples/*/*.py
        mv ./locale/examples ./pyvista/docs
        git submodule update --remote
        (cd pyvista; make -C docs html -b coverage; make -C docs doctest; make -C docs html)
        sh ./locale/update.sh
        ls ./pyvista/docs/examples
        mv ./pyvista/docs/examples ./locale
        ls ./pyvista/docs/images
        rm -Rf ./locale/images
        mv ./pyvista/docs/images ./locale
        deactivate
    - name: commit
      if: contains(github.event.head_commit.message, '[ci skip]') == false && contains(github.ref, 'master')
      env:
        JOB_ID: ${{ steps.jobs.outputs.job_id }}
        HTML_URL: ${{ steps.jobs.outputs.html_url }}
      run: |
        git config --global user.email $GITHUB_REPOSITORY
        git config --global user.name $GITHUB_REPOSITORY
        git add .
        git commit --allow-empty -m "[ci skip] $JOB_ID
        $HTML_URL"
        git remote -v
        git remote add github git@github.com:$GITHUB_REPOSITORY.git
        git push github master
