name: pyvista-doc-auto-update

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    env:
      SPHINXINTL_TRANSIFEX_ORGANIZATION_NAME: tkoyama010
      SPHINXINTL_TRANSIFEX_USERNAME: api
      SPHINXINTL_TRANSIFEX_PROJECT_NAME: pyvista-doc
      TX_TOKEN: ${{ secrets.TX_TOKEN }}

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Get date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        echo "::set-output name=yyyymm::$(/bin/date -u "+%Y%m")"
      shell: bash
    - name: cache pip
      id: cache-pip
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.local/
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ steps.get-date.outputs.yyyymm }}
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Check Python version
      run: python --version
      - uses: awalsh128/cache-apt-pkgs-action@v1.1.3
        with:
          packages: libosmesa6-dev libgl1-mesa-dev python3-tk pandoc git-restore-mtime
          version: 3.0
    - name: Install dependencies
      run: |
        git submodule init
        git submodule update
        pip install -U pip setuptools wheel
        pip install -r ./requirements.txt
    - name: Install Transifex CLI
      run: |
        curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
        mv tx /usr/local/bin/tx
    - name: Update translations
      run: |
        set -x
        export DISPLAY=:99.0
        export PYVISTA_OFF_SCREEN=True
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        sleep 3
        set +x
        rm ./locale/examples/*/*.py
        mv ./locale/examples ./pyvista/doc/source
        cd pyvista
        make -C doc html SPHINXOPTS="-w build_errors.txt -N"
        cd ../
        sh ./locale/update.sh
        ls ./pyvista/doc/source/examples
        mv ./pyvista/doc/source/examples ./locale
        ls ./pyvista/doc/source/images
        rm -Rf ./locale/images
        mv ./pyvista/doc/source/images ./locale
    - name: After success
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[skip ci] by GHA https://github.com/${{ github.repository }}/actions/runs/${{ github.run_number }}"
