# This workflow will run lint
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python Code Quality and Lint
      uses: ricardochaves/python-lint@v1.1.0
      with:
        python-root-list: conf.py
        use-pylint: true
        use-pycodestyle: true
        use-flake8: true
        use-black: true
        use-mypy: false
        use-isort: true
        extra-pylint-options: --disable=F0010
